BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        BoxLayout:
            TextInput:
                id: input_miles
            BoxLayout:
                orientation: 'vertical'
                size_hint_x: 0.2
                Button:
                    text: 'Up'
                    font_size: 50
                    on_press: app.handle_increment(1)
                Button:
                    text: 'Down'
                    font_size: 50
                    on_press: app.handle_increment(-1)
    Button:
        text: 'Convert miles to km'
        font_size: 50
        on_press: app.calculate()
    Label:
        id: km_text
        text: app.message
        font_size: 50
        color: (1, 1, 0, 1)
